/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
	ethers,
	EventFilter,
	Signer,
	BigNumber,
	BigNumberish,
	PopulatedTransaction,
	BaseContract,
	ContractTransaction,
	Overrides,
	CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HostingPaymentInterface extends ethers.utils.Interface {
	functions: {
		"MaxTotalExpiration()": FunctionFragment;
		"MinExpiration()": FunctionFragment;
		"addCombo((uint256,uint256,uint256,uint256,bool,string))": FunctionFragment;
		"addToken(address)": FunctionFragment;
		"buy(bytes28,uint256,uint256,uint256)": FunctionFragment;
		"canBuy(bytes28,uint256)": FunctionFragment;
		"canRenew(bytes28)": FunctionFragment;
		"canUpgrade(bytes28,uint256)": FunctionFragment;
		"comboLength()": FunctionFragment;
		"combos(uint256)": FunctionFragment;
		"expiration(bytes28)": FunctionFragment;
		"expirationAt(bytes28)": FunctionFragment;
		"gId()": FunctionFragment;
		"getComboCost(uint256,uint256)": FunctionFragment;
		"getUpgradeExchange(bytes28,uint256)": FunctionFragment;
		"guid(bytes28)": FunctionFragment;
		"isExpired(bytes28)": FunctionFragment;
		"lock()": FunctionFragment;
		"maxTotalRenewExpiration(bytes28)": FunctionFragment;
		"maxTotalUpgradeExpiration(bytes28,uint256)": FunctionFragment;
		"nonces(bytes28)": FunctionFragment;
		"owner()": FunctionFragment;
		"receipts(bytes28)": FunctionFragment;
		"removeToken(uint256)": FunctionFragment;
		"renew(uint256,bytes28,uint256,uint256)": FunctionFragment;
		"serviceId()": FunctionFragment;
		"setMaxTotalExpriation(uint256)": FunctionFragment;
		"setMinExpriation(uint256)": FunctionFragment;
		"tokenLength()": FunctionFragment;
		"tokens(uint256)": FunctionFragment;
		"transferOwnership(address)": FunctionFragment;
		"unlock()": FunctionFragment;
		"updateCombo(uint256,(uint256,uint256,uint256,uint256,bool,string))": FunctionFragment;
		"upgrade(bytes28,uint256,uint256,uint256)": FunctionFragment;
		"validateCombo(uint256)": FunctionFragment;
		"withdraw(address,address,uint256)": FunctionFragment;
	};

	encodeFunctionData(
		functionFragment: "MaxTotalExpiration",
		values?: undefined
	): string;
	encodeFunctionData(
		functionFragment: "MinExpiration",
		values?: undefined
	): string;
	encodeFunctionData(
		functionFragment: "addCombo",
		values: [
			{
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			}
		]
	): string;
	encodeFunctionData(functionFragment: "addToken", values: [string]): string;
	encodeFunctionData(
		functionFragment: "buy",
		values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "canBuy",
		values: [BytesLike, BigNumberish]
	): string;
	encodeFunctionData(functionFragment: "canRenew", values: [BytesLike]): string;
	encodeFunctionData(
		functionFragment: "canUpgrade",
		values: [BytesLike, BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "comboLength",
		values?: undefined
	): string;
	encodeFunctionData(
		functionFragment: "combos",
		values: [BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "expiration",
		values: [BytesLike]
	): string;
	encodeFunctionData(
		functionFragment: "expirationAt",
		values: [BytesLike]
	): string;
	encodeFunctionData(functionFragment: "gId", values?: undefined): string;
	encodeFunctionData(
		functionFragment: "getComboCost",
		values: [BigNumberish, BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "getUpgradeExchange",
		values: [BytesLike, BigNumberish]
	): string;
	encodeFunctionData(functionFragment: "guid", values: [BytesLike]): string;
	encodeFunctionData(
		functionFragment: "isExpired",
		values: [BytesLike]
	): string;
	encodeFunctionData(functionFragment: "lock", values?: undefined): string;
	encodeFunctionData(
		functionFragment: "maxTotalRenewExpiration",
		values: [BytesLike]
	): string;
	encodeFunctionData(
		functionFragment: "maxTotalUpgradeExpiration",
		values: [BytesLike, BigNumberish]
	): string;
	encodeFunctionData(functionFragment: "nonces", values: [BytesLike]): string;
	encodeFunctionData(functionFragment: "owner", values?: undefined): string;
	encodeFunctionData(functionFragment: "receipts", values: [BytesLike]): string;
	encodeFunctionData(
		functionFragment: "removeToken",
		values: [BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "renew",
		values: [BigNumberish, BytesLike, BigNumberish, BigNumberish]
	): string;
	encodeFunctionData(functionFragment: "serviceId", values?: undefined): string;
	encodeFunctionData(
		functionFragment: "setMaxTotalExpriation",
		values: [BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "setMinExpriation",
		values: [BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "tokenLength",
		values?: undefined
	): string;
	encodeFunctionData(
		functionFragment: "tokens",
		values: [BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "transferOwnership",
		values: [string]
	): string;
	encodeFunctionData(functionFragment: "unlock", values?: undefined): string;
	encodeFunctionData(
		functionFragment: "updateCombo",
		values: [
			BigNumberish,
			{
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			}
		]
	): string;
	encodeFunctionData(
		functionFragment: "upgrade",
		values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "validateCombo",
		values: [BigNumberish]
	): string;
	encodeFunctionData(
		functionFragment: "withdraw",
		values: [string, string, BigNumberish]
	): string;

	decodeFunctionResult(
		functionFragment: "MaxTotalExpiration",
		data: BytesLike
	): Result;
	decodeFunctionResult(
		functionFragment: "MinExpiration",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "addCombo", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "addToken", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "canBuy", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "canRenew", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "canUpgrade", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "comboLength",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "combos", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "expiration", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "expirationAt",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "gId", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "getComboCost",
		data: BytesLike
	): Result;
	decodeFunctionResult(
		functionFragment: "getUpgradeExchange",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "guid", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "isExpired", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "lock", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "maxTotalRenewExpiration",
		data: BytesLike
	): Result;
	decodeFunctionResult(
		functionFragment: "maxTotalUpgradeExpiration",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "nonces", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "removeToken",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "renew", data: BytesLike): Result;
	decodeFunctionResult(functionFragment: "serviceId", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "setMaxTotalExpriation",
		data: BytesLike
	): Result;
	decodeFunctionResult(
		functionFragment: "setMinExpriation",
		data: BytesLike
	): Result;
	decodeFunctionResult(
		functionFragment: "tokenLength",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "tokens", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "transferOwnership",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "unlock", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "updateCombo",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "upgrade", data: BytesLike): Result;
	decodeFunctionResult(
		functionFragment: "validateCombo",
		data: BytesLike
	): Result;
	decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

	events: {
		"Buy(bytes2,bytes2,bytes28,tuple)": EventFragment;
		"Renew(bytes2,bytes2,bytes28,tuple)": EventFragment;
		"Upgrade(bytes2,bytes2,bytes28,tuple)": EventFragment;
	};

	getEvent(nameOrSignatureOrTopic: "Buy"): EventFragment;
	getEvent(nameOrSignatureOrTopic: "Renew"): EventFragment;
	getEvent(nameOrSignatureOrTopic: "Upgrade"): EventFragment;
}

export type BuyEvent = TypedEvent<
	[
		string,
		string,
		string,
		[
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		}
	] & {
		gId_: string;
		serviceId_: string;
		uuid: string;
		receipt: [
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		};
	}
>;

export type RenewEvent = TypedEvent<
	[
		string,
		string,
		string,
		[
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		}
	] & {
		gId_: string;
		serviceId_: string;
		uuid: string;
		receipt: [
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		};
	}
>;

export type UpgradeEvent = TypedEvent<
	[
		string,
		string,
		string,
		[
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		}
	] & {
		gId_: string;
		serviceId_: string;
		uuid: string;
		receipt: [
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		};
	}
>;

export class HostingPayment extends BaseContract {
	connect(signerOrProvider: Signer | Provider | string): this;
	attach(addressOrName: string): this;
	deployed(): Promise<this>;

	listeners<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
	): Array<TypedListener<EventArgsArray, EventArgsObject>>;
	off<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this;
	on<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this;
	once<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this;
	removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
		listener: TypedListener<EventArgsArray, EventArgsObject>
	): this;
	removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
		eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
	): this;

	listeners(eventName?: string): Array<Listener>;
	off(eventName: string, listener: Listener): this;
	on(eventName: string, listener: Listener): this;
	once(eventName: string, listener: Listener): this;
	removeListener(eventName: string, listener: Listener): this;
	removeAllListeners(eventName?: string): this;

	queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
		event: TypedEventFilter<EventArgsArray, EventArgsObject>,
		fromBlockOrBlockhash?: string | number | undefined,
		toBlock?: string | number | undefined
	): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

	interface: HostingPaymentInterface;

	functions: {
		MaxTotalExpiration(overrides?: CallOverrides): Promise<[BigNumber]>;

		MinExpiration(overrides?: CallOverrides): Promise<[BigNumber]>;

		addCombo(
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		addToken(
			token: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		buy(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		canBuy(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<[boolean]>;

		canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

		canUpgrade(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<[boolean]>;

		comboLength(overrides?: CallOverrides): Promise<[BigNumber]>;

		combos(
			arg0: BigNumberish,
			overrides?: CallOverrides
		): Promise<
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		>;

		expiration(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<[BigNumber]>;

		expirationAt(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<[BigNumber]>;

		gId(overrides?: CallOverrides): Promise<[string]>;

		getComboCost(
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<[BigNumber] & { cost: BigNumber }>;

		getUpgradeExchange(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<[BigNumber] & { expiration_: BigNumber }>;

		guid(uuid: BytesLike, overrides?: CallOverrides): Promise<[string]>;

		isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<[boolean]>;

		lock(
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		maxTotalRenewExpiration(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<[BigNumber]>;

		maxTotalUpgradeExpiration(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<[BigNumber]>;

		nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<[BigNumber]>;

		owner(overrides?: CallOverrides): Promise<[string]>;

		receipts(
			arg0: BytesLike,
			overrides?: CallOverrides
		): Promise<
			[
				string,
				string,
				BigNumber,
				BigNumber,
				BigNumber,
				BigNumber,
				BigNumber,
				[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
					bandwidth: BigNumber;
					storageAmount: BigNumber;
					buildingTime: BigNumber;
					pricePerMonth: BigNumber;
					isValid: boolean;
					name: string;
				}
			] & {
				to: string;
				token: string;
				level: BigNumber;
				boughtTime: BigNumber;
				expiration: BigNumber;
				expectedCost: BigNumber;
				realCost: BigNumber;
				combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
					bandwidth: BigNumber;
					storageAmount: BigNumber;
					buildingTime: BigNumber;
					pricePerMonth: BigNumber;
					isValid: boolean;
					name: string;
				};
			}
		>;

		removeToken(
			index: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		renew(
			nonce: BigNumberish,
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		serviceId(overrides?: CallOverrides): Promise<[string]>;

		setMaxTotalExpriation(
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		setMinExpriation(
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		tokenLength(overrides?: CallOverrides): Promise<[BigNumber]>;

		tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

		transferOwnership(
			newOwner: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		unlock(
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		updateCombo(
			level: BigNumberish,
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		upgrade(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			moreExpiration: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;

		validateCombo(
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<[void]>;

		withdraw(
			token: string,
			to: string,
			value: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<ContractTransaction>;
	};

	MaxTotalExpiration(overrides?: CallOverrides): Promise<BigNumber>;

	MinExpiration(overrides?: CallOverrides): Promise<BigNumber>;

	addCombo(
		combo: {
			bandwidth: BigNumberish;
			storageAmount: BigNumberish;
			buildingTime: BigNumberish;
			pricePerMonth: BigNumberish;
			isValid: boolean;
			name: string;
		},
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	addToken(
		token: string,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	buy(
		uuid: BytesLike,
		tokenIndex: BigNumberish,
		level: BigNumberish,
		expiration_: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	canBuy(
		uuid: BytesLike,
		level: BigNumberish,
		overrides?: CallOverrides
	): Promise<boolean>;

	canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

	canUpgrade(
		uuid: BytesLike,
		level: BigNumberish,
		overrides?: CallOverrides
	): Promise<boolean>;

	comboLength(overrides?: CallOverrides): Promise<BigNumber>;

	combos(
		arg0: BigNumberish,
		overrides?: CallOverrides
	): Promise<
		[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
			bandwidth: BigNumber;
			storageAmount: BigNumber;
			buildingTime: BigNumber;
			pricePerMonth: BigNumber;
			isValid: boolean;
			name: string;
		}
	>;

	expiration(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

	expirationAt(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

	gId(overrides?: CallOverrides): Promise<string>;

	getComboCost(
		level: BigNumberish,
		expiration_: BigNumberish,
		overrides?: CallOverrides
	): Promise<BigNumber>;

	getUpgradeExchange(
		uuid: BytesLike,
		level: BigNumberish,
		overrides?: CallOverrides
	): Promise<BigNumber>;

	guid(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

	isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

	lock(
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	maxTotalRenewExpiration(
		uuid: BytesLike,
		overrides?: CallOverrides
	): Promise<BigNumber>;

	maxTotalUpgradeExpiration(
		uuid: BytesLike,
		level: BigNumberish,
		overrides?: CallOverrides
	): Promise<BigNumber>;

	nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

	owner(overrides?: CallOverrides): Promise<string>;

	receipts(
		arg0: BytesLike,
		overrides?: CallOverrides
	): Promise<
		[
			string,
			string,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			BigNumber,
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		] & {
			to: string;
			token: string;
			level: BigNumber;
			boughtTime: BigNumber;
			expiration: BigNumber;
			expectedCost: BigNumber;
			realCost: BigNumber;
			combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			};
		}
	>;

	removeToken(
		index: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	renew(
		nonce: BigNumberish,
		uuid: BytesLike,
		tokenIndex: BigNumberish,
		expiration_: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	serviceId(overrides?: CallOverrides): Promise<string>;

	setMaxTotalExpriation(
		expiration_: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	setMinExpriation(
		expiration_: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	tokenLength(overrides?: CallOverrides): Promise<BigNumber>;

	tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

	transferOwnership(
		newOwner: string,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	unlock(
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	updateCombo(
		level: BigNumberish,
		combo: {
			bandwidth: BigNumberish;
			storageAmount: BigNumberish;
			buildingTime: BigNumberish;
			pricePerMonth: BigNumberish;
			isValid: boolean;
			name: string;
		},
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	upgrade(
		uuid: BytesLike,
		tokenIndex: BigNumberish,
		level: BigNumberish,
		moreExpiration: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	validateCombo(level: BigNumberish, overrides?: CallOverrides): Promise<void>;

	withdraw(
		token: string,
		to: string,
		value: BigNumberish,
		overrides?: Overrides & { from?: string | Promise<string> }
	): Promise<ContractTransaction>;

	callStatic: {
		MaxTotalExpiration(overrides?: CallOverrides): Promise<BigNumber>;

		MinExpiration(overrides?: CallOverrides): Promise<BigNumber>;

		addCombo(
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: CallOverrides
		): Promise<void>;

		addToken(token: string, overrides?: CallOverrides): Promise<void>;

		buy(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		canBuy(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<boolean>;

		canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

		canUpgrade(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<boolean>;

		comboLength(overrides?: CallOverrides): Promise<BigNumber>;

		combos(
			arg0: BigNumberish,
			overrides?: CallOverrides
		): Promise<
			[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
				bandwidth: BigNumber;
				storageAmount: BigNumber;
				buildingTime: BigNumber;
				pricePerMonth: BigNumber;
				isValid: boolean;
				name: string;
			}
		>;

		expiration(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		expirationAt(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		gId(overrides?: CallOverrides): Promise<string>;

		getComboCost(
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		getUpgradeExchange(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		guid(uuid: BytesLike, overrides?: CallOverrides): Promise<string>;

		isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<boolean>;

		lock(overrides?: CallOverrides): Promise<void>;

		maxTotalRenewExpiration(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		maxTotalUpgradeExpiration(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		owner(overrides?: CallOverrides): Promise<string>;

		receipts(
			arg0: BytesLike,
			overrides?: CallOverrides
		): Promise<
			[
				string,
				string,
				BigNumber,
				BigNumber,
				BigNumber,
				BigNumber,
				BigNumber,
				[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
					bandwidth: BigNumber;
					storageAmount: BigNumber;
					buildingTime: BigNumber;
					pricePerMonth: BigNumber;
					isValid: boolean;
					name: string;
				}
			] & {
				to: string;
				token: string;
				level: BigNumber;
				boughtTime: BigNumber;
				expiration: BigNumber;
				expectedCost: BigNumber;
				realCost: BigNumber;
				combo: [BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
					bandwidth: BigNumber;
					storageAmount: BigNumber;
					buildingTime: BigNumber;
					pricePerMonth: BigNumber;
					isValid: boolean;
					name: string;
				};
			}
		>;

		removeToken(index: BigNumberish, overrides?: CallOverrides): Promise<void>;

		renew(
			nonce: BigNumberish,
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		serviceId(overrides?: CallOverrides): Promise<string>;

		setMaxTotalExpriation(
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<void>;

		setMinExpriation(
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<void>;

		tokenLength(overrides?: CallOverrides): Promise<BigNumber>;

		tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

		transferOwnership(
			newOwner: string,
			overrides?: CallOverrides
		): Promise<void>;

		unlock(overrides?: CallOverrides): Promise<void>;

		updateCombo(
			level: BigNumberish,
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: CallOverrides
		): Promise<void>;

		upgrade(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			moreExpiration: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		validateCombo(
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<void>;

		withdraw(
			token: string,
			to: string,
			value: BigNumberish,
			overrides?: CallOverrides
		): Promise<void>;
	};

	filters: {
		"Buy(bytes2,bytes2,bytes28,tuple)"(
			gId_?: BytesLike | null,
			serviceId_?: BytesLike | null,
			uuid?: BytesLike | null,
			receipt?: null
		): TypedEventFilter<
			[
				string,
				string,
				string,
				[
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				}
			],
			{
				gId_: string;
				serviceId_: string;
				uuid: string;
				receipt: [
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				};
			}
		>;

		Buy(
			gId_?: BytesLike | null,
			serviceId_?: BytesLike | null,
			uuid?: BytesLike | null,
			receipt?: null
		): TypedEventFilter<
			[
				string,
				string,
				string,
				[
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				}
			],
			{
				gId_: string;
				serviceId_: string;
				uuid: string;
				receipt: [
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				};
			}
		>;

		"Renew(bytes2,bytes2,bytes28,tuple)"(
			gId_?: BytesLike | null,
			serviceId_?: BytesLike | null,
			uuid?: BytesLike | null,
			receipt?: null
		): TypedEventFilter<
			[
				string,
				string,
				string,
				[
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				}
			],
			{
				gId_: string;
				serviceId_: string;
				uuid: string;
				receipt: [
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				};
			}
		>;

		Renew(
			gId_?: BytesLike | null,
			serviceId_?: BytesLike | null,
			uuid?: BytesLike | null,
			receipt?: null
		): TypedEventFilter<
			[
				string,
				string,
				string,
				[
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				}
			],
			{
				gId_: string;
				serviceId_: string;
				uuid: string;
				receipt: [
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				};
			}
		>;

		"Upgrade(bytes2,bytes2,bytes28,tuple)"(
			gId_?: BytesLike | null,
			serviceId_?: BytesLike | null,
			uuid?: BytesLike | null,
			receipt?: null
		): TypedEventFilter<
			[
				string,
				string,
				string,
				[
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				}
			],
			{
				gId_: string;
				serviceId_: string;
				uuid: string;
				receipt: [
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				};
			}
		>;

		Upgrade(
			gId_?: BytesLike | null,
			serviceId_?: BytesLike | null,
			uuid?: BytesLike | null,
			receipt?: null
		): TypedEventFilter<
			[
				string,
				string,
				string,
				[
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				}
			],
			{
				gId_: string;
				serviceId_: string;
				uuid: string;
				receipt: [
					string,
					string,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					BigNumber,
					[BigNumber, BigNumber, BigNumber, BigNumber, boolean, string] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					}
				] & {
					to: string;
					token: string;
					level: BigNumber;
					boughtTime: BigNumber;
					expiration: BigNumber;
					expectedCost: BigNumber;
					realCost: BigNumber;
					combo: [
						BigNumber,
						BigNumber,
						BigNumber,
						BigNumber,
						boolean,
						string
					] & {
						bandwidth: BigNumber;
						storageAmount: BigNumber;
						buildingTime: BigNumber;
						pricePerMonth: BigNumber;
						isValid: boolean;
						name: string;
					};
				};
			}
		>;
	};

	estimateGas: {
		MaxTotalExpiration(overrides?: CallOverrides): Promise<BigNumber>;

		MinExpiration(overrides?: CallOverrides): Promise<BigNumber>;

		addCombo(
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		addToken(
			token: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		buy(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		canBuy(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		canRenew(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		canUpgrade(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		comboLength(overrides?: CallOverrides): Promise<BigNumber>;

		combos(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

		expiration(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		expirationAt(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		gId(overrides?: CallOverrides): Promise<BigNumber>;

		getComboCost(
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		getUpgradeExchange(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		guid(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		isExpired(uuid: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		lock(
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		maxTotalRenewExpiration(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		maxTotalUpgradeExpiration(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		nonces(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		owner(overrides?: CallOverrides): Promise<BigNumber>;

		receipts(arg0: BytesLike, overrides?: CallOverrides): Promise<BigNumber>;

		removeToken(
			index: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		renew(
			nonce: BigNumberish,
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		serviceId(overrides?: CallOverrides): Promise<BigNumber>;

		setMaxTotalExpriation(
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		setMinExpriation(
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		tokenLength(overrides?: CallOverrides): Promise<BigNumber>;

		tokens(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

		transferOwnership(
			newOwner: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		unlock(
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		updateCombo(
			level: BigNumberish,
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		upgrade(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			moreExpiration: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;

		validateCombo(
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<BigNumber>;

		withdraw(
			token: string,
			to: string,
			value: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<BigNumber>;
	};

	populateTransaction: {
		MaxTotalExpiration(
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		MinExpiration(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		addCombo(
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		addToken(
			token: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		buy(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		canBuy(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		canRenew(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		canUpgrade(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		comboLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		combos(
			arg0: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		expiration(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		expirationAt(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		gId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		getComboCost(
			level: BigNumberish,
			expiration_: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		getUpgradeExchange(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		guid(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		isExpired(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		lock(
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		maxTotalRenewExpiration(
			uuid: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		maxTotalUpgradeExpiration(
			uuid: BytesLike,
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		nonces(
			arg0: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		receipts(
			arg0: BytesLike,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		removeToken(
			index: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		renew(
			nonce: BigNumberish,
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		serviceId(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		setMaxTotalExpriation(
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		setMinExpriation(
			expiration_: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		tokenLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

		tokens(
			arg0: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		transferOwnership(
			newOwner: string,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		unlock(
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		updateCombo(
			level: BigNumberish,
			combo: {
				bandwidth: BigNumberish;
				storageAmount: BigNumberish;
				buildingTime: BigNumberish;
				pricePerMonth: BigNumberish;
				isValid: boolean;
				name: string;
			},
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		upgrade(
			uuid: BytesLike,
			tokenIndex: BigNumberish,
			level: BigNumberish,
			moreExpiration: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;

		validateCombo(
			level: BigNumberish,
			overrides?: CallOverrides
		): Promise<PopulatedTransaction>;

		withdraw(
			token: string,
			to: string,
			value: BigNumberish,
			overrides?: Overrides & { from?: string | Promise<string> }
		): Promise<PopulatedTransaction>;
	};
}
